server:
  port: 6004

spring:
  application:
    name: datapillar-job-server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/datapillar?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: Sunny.123456
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 30000
      pool-name: DatapillarJobHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000

mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: com.sunny.job.server.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: isDeleted
      logic-delete-value: 1
      logic-not-delete-value: 0

logging:
  level:
    root: INFO
    com.sunny.job: DEBUG

# worker日志 配置
datapillar:
  job:
    worker:
      # 任务日志配置
      log:
        # 日志存储根目录（与 Worker 配置相同路径，共享存储）
        base-path: ${LOG_HOME:/tmp/logs}/job
